In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.options.display.max_info_columns=500
pd.options.display.max_info_rows=550
from sklearn import set_config; set_config(display='diagram')
from sklearn.model_selection import train_test_split, cross_val_score
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_percentage_error

In [3]:
from carbon_forecast.utils.preproc import load_n_preproc_all_avail
df = load_n_preproc_all_avail()
X = df.drop(columns=["company_name", "TCUID", "year", "intensity_1and2","intensity_scope3"])
y = df["intensity_1and2"]

Reading data...
Preproc on power % revenue
Preproc on Sector Revenue
Selecting the year 2013 required...
Dropping rows that are showing NaN on...
-> intensity_scope1CY2013
-> intensity_scope2CY2013
-> intensity_scope3CY2013
-> Revenue2013
Filling employee numbers with mean value... (subject to change later)
Filling EV with mean value... (subject to change later)
Calculating Employees & EV per Revenue...
Filling null Climate Strategy Score with 0...
Cleaning P/E Ratio...
Adding Scope 1 and Scope 2 data together...
Doing some column renaming...
Filling in Disclosure...
Dataset preproc-ed for the year 2013!👍
Reading data...
Preproc on power % revenue
Preproc on Sector Revenue
Selecting the year 2014 required...
Dropping rows that are showing NaN on...
-> intensity_scope1CY2014
-> intensity_scope2CY2014
-> intensity_scope3CY2014
-> Revenue2014
Filling employee numbers with mean value... (subject to change later)
Filling EV with mean value... (subject to change later)
Calculating Employees 

In [4]:
X.drop(columns=["pe_rat", "EV / Revenue", "revenue"], inplace=True)
X

Sector  Employees / Revenue  climate_strategy_score  \
3      Communication Services             7.404388                     0.0   
19     Information Technology             3.352162                     0.0   
20                 Financials             0.396287                    56.0   
22                Industrials             3.077321                    62.0   
25     Information Technology           969.400829                     0.0   
...                       ...                  ...                     ...   
16642             Health Care            11.807807                     0.0   
16643        Consumer Staples             4.312798                     0.0   
16644               Materials            37.789822                     0.0   
16645             Health Care            11.681343                     0.0   
16646             Health Care             9.660268                     0.0   

       disclosure  nuclear_percentage_revenue  \
3        0.000000                         0.0   
19       0.000000                         0.0   
20       0.000000                         0.0   
22      99.997365                         0.0   
25       0.000000                         0.0   
...           ...                         ...   
16642   99.047000                         0.0   
16643    0.000000                         0.0   
16644    0.000000                         0.0   
16645    0.000000                         0.0   
16646    0.000000                         0.0   

       thermal_coal_percentage_revenue  \
3                                  0.0   
19                                 0.0   
20                                 0.0   
22                                 0.0   
25                                 0.0   
...                                ...   
16642                              0.0   
16643                              0.0   
16644                              0.0   
16645                              0.0   
16646                              0.0   

       ultra_deep_sea_drilling_percentage_revenue  \
3                                             0.0   
19                                            0.0   
20                                            0.0   
22                                            0.0   
25                                            0.0   
...                                           ...   
16642                                         0.0   
16643                                         0.0   
16644                                         0.0   
16645                                         0.0   
16646                                         0.0   

       shale_oil_gas_percentage_revenue  coal_percentage_revenue  \
3                                   0.0                      0.0   
19                                  0.0                      0.0   
20                                  0.0                      0.0   
22                                  0.0                      0.0   
25                                  0.0                      0.0   
...                                 ...                      ...   
16642                               0.0                      0.0   
16643                               0.0                      0.0   
16644                               0.0                      0.0   
16645                               0.0                      0.0   
16646                               0.0                      0.0   

       arctic_drilling_percentage_revenue  oil_sands_percentage_revenue  \
3                                     0.0                           0.0   
19                                    0.0                           0.0   
20                                    0.0                           0.0   
22                                    0.0                           0.0   
25                                    0.0                           0.0   
...                                   ...                           ...   
16642        

In [28]:
from carbon_forecast.utils.tx import our_tx, tt_split
transformer = our_tx(X)
X_train_transformed, X_test_transformed, y_train, y_test = tt_split(X,y,transformer)
X_train_transformed

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [29]:
from carbon_forecast.utils.pca import our_pca
X_proj, X_test_proj , pca= our_pca(X_train_transformed, X_test_transformed, 12)
X_proj

array([[ 5.90008302e-01, -5.08480575e-01,  9.89056270e-01, ...,
        -2.39227619e-02,  4.28646046e-02, -2.87775718e-01],
       [ 4.16209291e-01, -2.56349695e-01, -1.81050545e-01, ...,
        -8.02643412e-03,  6.61008547e-02, -2.68245409e-01],
       [-3.81946205e-01, -5.56579308e-02, -3.38345256e-02, ...,
        -2.32479507e-02,  2.75364690e-04, -8.85469795e-03],
       ...,
       [ 7.43997412e-01,  7.62334752e-01,  4.45691402e-02, ...,
        -1.13164068e-03,  7.69146534e-02, -2.73417599e-01],
       [-3.94746988e-01, -7.20874000e-02, -4.29878238e-02, ...,
        -7.30457195e-02, -3.50448966e-02, -3.93948724e-02],
       [-3.41664232e-01, -3.79812910e-01,  1.06364134e+00, ...,
        -3.20653207e-02, -3.76756612e-02,  2.12289899e-03]])

In [30]:
model = XGBRegressor(n_estimators=1000, max_depth=10, objective="reg:squarederror", eval_metric="mape")
cross_val_score(model, X_proj, y_train, cv=5, scoring="neg_mean_absolute_percentage_error")

array([-3.70783288, -1.54990042, -2.3384149 , -3.77202656, -1.67950267])

In [31]:
model.fit(X_proj,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric='mape', gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=10, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=1000,
             n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
             reg_alpha=0, reg_lambda=1, ...)

In [16]:
pca

PCA(n_components=12)

In [32]:
file = open("tx_norevenue_0914.pkl", "wb")
pickle.dump(transformer, file)
file.close()
file = open("pca_norevenue_0914.pkl", "wb")
pickle.dump(pca, file)
file.close()

In [33]:
model.save_model("model_norevenue_0914.json")

In [34]:
y_pred = model.predict(X_test_proj)
mean_absolute_percentage_error(y_test, y_pred)

2.173660892196677