In [28]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.options.display.max_info_columns=500
pd.options.display.max_info_rows=550
from tensorflow.keras.losses import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler
from sklearn.compose import ColumnTransformer
from sklearn import set_config; set_config(display='diagram')
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV, cross_val_score, GridSearchCV
from xgboost import XGBRegressor, Booster

from carbon_forecast.utils.preproc import load_n_preproc_all_avail
df = load_n_preproc_all_avail()
X = df.drop(columns=["company_name", "TCUID", "year", "intensity_1and2","intensity_scope3"])
y = df["intensity_1and2"]

Reading data...
Preproc on power % revenue
Preproc on Sector Revenue
Selecting the year 2013 required...
Dropping rows that are showing NaN on...
-> intensity_scope1CY2013
-> intensity_scope2CY2013
-> intensity_scope3CY2013
-> Revenue2013
Filling employee numbers with mean value... (subject to change later)
Filling EV with mean value... (subject to change later)
Calculating Employees & EV per Revenue...
Filling null Climate Strategy Score with 0...
Cleaning P/E Ratio...
Adding Scope 1 and Scope 2 data together...
Doing some column renaming...
Dataset preproc-ed for the year 2013!👍
Reading data...
Preproc on power % revenue
Preproc on Sector Revenue
Selecting the year 2014 required...
Dropping rows that are showing NaN on...
-> intensity_scope1CY2014
-> intensity_scope2CY2014
-> intensity_scope3CY2014
-> Revenue2014
Filling employee numbers with mean value... (subject to change later)
Filling EV with mean value... (subject to change later)
Calculating Employees & EV per Revenue...
Filli

In [2]:
X.shape

(85099, 458)

In [13]:
rdn = np.random.randint(0,85099)
X_to_test = X.iloc[rdn,:]
y_to_test = y.iloc[rdn]
X_to_test

Sector                                                  Consumer Staples
Employees / Revenue                                             2.839109
EV / Revenue                                                    3.235569
climate_strategy_score                                              10.0
disclosure                                                           0.0
                                                              ...       
Wiring device manufacturing                                          0.0
Women's and girls' cut and sew apparel manufacturing                 0.0
Wood container and pallet manufacturing                              0.0
Wood kitchen cabinet and countertop manufacturing                    0.0
Wood windows and doors and millwork                                  0.0
Name: 8071, Length: 458, dtype: object

In [14]:
X_to_test.to_csv("X_to_test.csv", index=False)

In [25]:
X_test2 = pd.read_csv("../tests/X_2.csv")
X_2 = np.array(X_test2).reshape(1,468)

In [26]:
loaded = pickle.load(open("../tests/xgboost_loaded.pkl", "rb"))
loaded.predict(X_2)

array([5.641958], dtype=float32)

In [44]:
import xgboost as xgb
model = xgb.Booster()
testload = model.load_model("test.json")

In [45]:
X_2

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.000000

In [46]:
testload.predict(X_2)

AttributeError: 'NoneType' object has no attribute 'predict'

In [47]:
import joblib

In [48]:
testie = joblib.load("test3.sav")


In [49]:
testie.predict(X_2)

array([5.641958], dtype=float32)